### ISSUE TITLE
this is more of a question than an issue

### ISSUE THREAD

**Issue by silvacarl2** [rafael-ariascalles/whisper-fine-tuning-docker#3]
hi, we have 12M names and we would like to fine tune whisper on them.  also, i am happy to share with you the results.

the question is it better to fine tune whisper using the entire spoken name?  Or is it better to fine tune using invidial names and recording snippets of each anme spoken?

**Comment by rafael-ariascalles** [comment]
Hey, I think that the best approach will be to use the entire name in context . But, all depends on your use case.

**Comment by silvacarl2** [comment]
thank you!!!!!!!!!!!!!!!!!!!!!
